"""
tools/git_tool.py
-----------------
Simple wrapper used by the IntegratorAgent to clone a starter repo
or to push the final generated repo to a remote.
"""

import os
import subprocess
from pathlib import Path
from typing import Dict, Any

class GitTool:
    def __init__(self, config: Dict[str, Any]):
        self.remote_url = config["remote_url"]
        self.branch = config.get("branch", "main")
        self.dest = Path(config.get("dest", "./output/repo"))

    async def __call__(self, **_) -> str:
        """If the dest folder exists, push; otherwise, init and push."""
        if not self.dest.exists():
            self.dest.mkdir(parents=True, exist_ok=True)

        # Initialise repo if needed
        if not (self.dest / ".git").exists():
            subprocess.run(["git", "init"], cwd=self.dest, check=True)
            subprocess.run(["git", "remote", "add", "origin", self.remote_url], cwd=self.dest, check=True)

        # Add, commit and push
        subprocess.run(["git", "add", "."], cwd=self.dest, check=True)
        subprocess.run(["git", "commit", "-m", "Generated by CrewAI"], cwd=self.dest, check=True)
        subprocess.run(["git", "push", "-u", "origin", self.branch], cwd=self.dest, check=True)

        return f"Pushed repo to {self.remote_url} (branch {self.branch})"
